Repository kdt5-3rd/kdt5-3rd-front, pull requests merged in 2025-05, with the labels that each got.

#38 style: 모바일 UI 최소너비 수정 및 설정 탭 데이터 변경
  src/app/(afterlogin)/calendar/_components/CalendarType.tsx
  src/app/(afterlogin)/calendar/daily/page.tsx
  src/app/(afterlogin)/calendar/monthly/page.tsx
  src/app/(afterlogin)/calendar/weekly/page.tsx
  src/app/(afterlogin)/news/page.tsx
  src/app/(afterlogin)/setting/EtcSetting.tsx
  src/app/(afterlogin)/setting/_settings/RouteSetting.tsx
  src/app/(afterlogin)/setting/page.tsx
  src/app/_components/nav/Navigation.tsx
  src/app/_components/tasks/LocationModal.tsx
  src/app/_components/tasks/TaskListItem.tsx
  src/app/page.tsx
Labels: style

#40 feat: 뉴스 카테고리 설정 기능 구현
  src/app/(afterlogin)/news/CategoryButton.tsx
  src/app/(afterlogin)/news/NewsCategory.tsx
  src/app/(afterlogin)/news/page.tsx
  src/app/(afterlogin)/setting/EtcSetting.tsx
  src/app/(afterlogin)/setting/_settings/NewsSetting.tsx
  src/app/store/newsCategoryStore.ts
Labels: enhancement

#41 fix: 일정 관리 버그 해결
  src/app/(afterlogin)/news/Articles.tsx
  src/app/_components/tasks/TaskListItem.tsx
  src/app/_components/tasks/TaskModal.tsx
  src/app/_utils/dateTimeUtil.ts
  src/app/page.tsx
Labels: bug

#42 release: v1.2.0
  src/app/(afterlogin)/calendar/_components/CalendarType.tsx
  src/app/(afterlogin)/calendar/daily/page.tsx
  src/app/(afterlogin)/calendar/monthly/page.tsx
  src/app/(afterlogin)/calendar/weekly/page.tsx
  src/app/(afterlogin)/news/Articles.tsx
  src/app/(afterlogin)/news/CategoryButton.tsx
  src/app/(afterlogin)/news/NewsCategory.tsx
  src/app/(afterlogin)/news/page.tsx
  src/app/(afterlogin)/setting/EtcSetting.tsx
  src/app/(afterlogin)/setting/_settings/NewsSetting.tsx
  src/app/(afterlogin)/setting/_settings/RouteSetting.tsx
  src/app/(afterlogin)/setting/page.tsx
  src/app/(afterlogin)/weather/page.tsx
  src/app/_components/common/NormalTextarea.tsx
  src/app/_components/nav/Navigation.tsx
  src/app/_components/tasks/LocationModal.tsx
  src/app/_components/tasks/TaskListItem.tsx
  src/app/_components/tasks/TaskModal.tsx
  src/app/_hooks/useGetWeatherQuery.ts
  src/app/_utils/dateTimeUtil.ts
  src/app/page.tsx
  src/app/store/newsCategoryStore.ts
Labels: enhancement

#43 fix: 길찾기 부분의 출발시각/도착시각 제거
  src/app/(afterlogin)/calendar/_components/RouteInfo.tsx
Labels: bug

#45 fix: 배경 높이 고정되어 나오는 문제 수정
  src/app/(afterlogin)/news/page.tsx
  src/app/(afterlogin)/weather/page.tsx
Labels: bug

#47 fix: 배경 높이 고정되어 나오는 문제 수정
  src/app/(afterlogin)/news/page.tsx
  src/app/(afterlogin)/weather/page.tsx
Labels: bug
